apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: civicpulse-prod
    target:
      kind: Namespace
      name: civicpulse
  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: prod
    target:
      kind: ConfigMap
      name: civicpulse-config
